// See lgfx_v1.cpp for the translation unit layout and maintenance notes.

#define LGFX_V1_IMPLEMENTATION

#include "panel/Panel_FrameBufferBase.inl"   // must precede platforms/esp32/Panel_EPD.inl (provides cacheWriteBack / Cache_WriteBack_Addr)
#include "platforms/esp32/common.inl"   // must precede the other esp32* files (provides reg() / writereg())
#include "platforms/esp32/Bus_EPD.inl"
#include "platforms/esp32/Bus_HUB75.inl"
#include "platforms/esp32/Bus_I2C.inl"
#include "platforms/esp32/Bus_Parallel8.inl"
#include "platforms/esp32/Bus_SPI.inl"
#include "platforms/esp32/Light_CH422G.inl"
#include "platforms/esp32/Light_PWM.inl"
#include "platforms/esp32/Panel_CVBS.inl"
#include "platforms/esp32/Panel_EPD.inl"
#include "platforms/esp32c3/Bus_Parallel8.inl"
#include "platforms/esp32p4/Bus_DSI.inl"
#include "platforms/esp32p4/Panel_DSI.inl"
#include "platforms/esp32p4/Panel_LT8912B.inl"
#include "platforms/esp32p4/Touch_ST7123.inl"
#include "platforms/esp32s2/Bus_Parallel16.inl"
#include "platforms/esp32s2/Bus_Parallel8.inl"
#include "platforms/esp32s3/Bus_Parallel16.inl"
#include "platforms/esp32s3/Bus_Parallel8.inl"
#include "platforms/esp32s3/Bus_RGB.inl"
#include "platforms/esp32s3/Panel_RGB.inl"
#include "platforms/arduino_default/Bus_SPI.inl"
#include "platforms/arduino_default/Bus_Stream.inl"
#include "platforms/arduino_default/common.inl"
#include "platforms/esp8266/Bus_I2C.inl"
#include "platforms/esp8266/Bus_SPI.inl"
#include "platforms/esp8266/common.inl"
#include "platforms/framebuffer/Panel_fb.inl"
#include "platforms/framebuffer/common.inl"
#include "platforms/opencv/Panel_OpenCV.inl"
#include "platforms/opencv/common.inl"
#include "platforms/rp2040/Bus_I2C.inl"
#include "platforms/rp2040/Bus_SPI.inl"
#include "platforms/rp2040/Light_PWM.inl"
#include "platforms/rp2040/common.inl"
#include "platforms/samd21/Bus_I2C.inl"
#include "platforms/samd21/Bus_SPI.inl"
#include "platforms/samd21/common.inl"
#include "platforms/samd51/Bus_I2C.inl"
#include "platforms/samd51/Bus_SPI.inl"
#include "platforms/samd51/common.inl"
#include "platforms/sdl/Panel_sdl.inl"
#include "platforms/sdl/common.inl"
#include "platforms/spresense/Bus_SPI.inl"
#include "platforms/spresense/common.inl"
#include "platforms/stm32/Bus_SPI.inl"
#include "platforms/stm32/common.inl"

#undef LGFX_V1_IMPLEMENTATION
