// See lgfx_v1.cpp for the translation unit layout and maintenance notes.

#define LGFX_V1_IMPLEMENTATION

#include "panel/Panel_AMOLED.inl"
#include "panel/Panel_Device.inl"
#include "panel/Panel_ED2208.inl"
#include "panel/Panel_EPDiy.inl"
#include "panel/Panel_FlexibleFrameBuffer.inl"
#include "panel/Panel_GDEW0154D67.inl"
#include "panel/Panel_GDEW0154M09.inl"
#include "panel/Panel_HUB75.inl"
#include "panel/Panel_HasBuffer.inl"
#include "panel/Panel_ILI9225.inl"
#include "panel/Panel_IT8951.inl"
#include "panel/Panel_LCD.inl"
#include "panel/Panel_M5UnitGLASS.inl"
#include "panel/Panel_M5UnitLCD.inl"
#include "panel/Panel_NT35510.inl"
#include "panel/Panel_NV3031B.inl"
#include "panel/Panel_NV3041A.inl"
#include "panel/Panel_RA8875.inl"
#include "panel/Panel_RM68120.inl"
#include "panel/Panel_SH8601Z.inl"
#include "panel/Panel_SSD1306.inl"
#include "panel/Panel_SSD1327.inl"
#include "panel/Panel_SSD1331.inl"
#include "panel/Panel_SSD1351.inl"
#include "panel/Panel_SSD1677.inl"
#include "panel/Panel_SSD1963.inl"
#include "panel/Panel_ST77916.inl"
#include "panel/Panel_SharpLCD.inl"
#include "panel/Panel_TM1680.inl"

#undef LGFX_V1_IMPLEMENTATION
