_ _ _ _ _ _ _ _ _ _ _ _ _ R R R R R R R _ _ _ _ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ _ _ R R R R R R R R R R R _ _ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ _ R R R R R R R R R R R R R _ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ R R R R _ _ _ _ _ _ R R R R R _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ R R R R R _ _ R R R _ _ R R R R R _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ R R R R R _ _ R R R _ _ R R R R R _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ R R R R R R _ _ _ _ _ _ R R R R R R R _ _ _ _ _ _ _
_ _ _ _ _ _ _ R R R R R R _ _ R R _ _ R R R R R R R _ _ _ _ _ _ _
_ _ _ _ _ _ _ R R R R R R _ _ R R R _ _ R R R R R R _ _ _ _ _ _ _
_ _ _ _ _ _ _ R R R R R R _ _ R R R _ _ R R R R R R _ _ _ _ _ _ _
_ _ _ _ _ _ _ R R R R R R _ _ R R R _ _ R R R R R R _ _ _ _ _ _ _
_ _ _ _ _ _ _ R R R R R R R R R R R R R R R R R R R _ _ _ _ _ _ _
_ _ _ _ _ _ G Y Y Y Y Y Y R R R R R R R M M M M M M B _ _ _ _ _ _
_ _ _ _ G G G G Y Y Y Y Y Y Y R R R M M M M M M M B B B B _ _ _ _
_ _ _ G G G G G Y Y Y Y Y Y Y Y R M M M M M M M M B B B B B _ _ _
_ _ G G G G G G G Y Y Y Y Y Y Y W M M M M M M M B B B B B B B _ _
_ G G G G G G G G G Y Y Y Y Y W W W M M M M M B B B B B B B B B _
_ G G G G G G G G G G Y Y Y Y W W W M M M M B B B B B B B B B B _
G G G G G G G G G G G G G Y W W W W W M B B B B B B B B B B B B B
G G G G G _ _ _ _ G G G G G C C C C C B B B B _ _ _ _ _ B B B B B
G G G G _ _ G G _ _ G G G G C C C C C B B B B _ _ B B _ _ B B B B
G G G G _ _ G G G G G G G G C C C C C B B B B _ _ B B _ _ B B B B
G G G G _ _ G G G G G G G G C C C C C B B B B _ _ _ _ _ B B B B B
G G G G _ _ G _ _ _ G G G G C C C C C B B B B _ _ B B _ _ B B B B
G G G G _ _ G G _ _ G G G G C C C C C B B B B _ _ B B _ _ B B B B
_ G G G _ _ G G _ _ G G G G G C C C B B B B B _ _ B B _ _ B B B _
_ G G G G _ _ _ _ G G G G G G C C C B B B B B _ _ _ _ _ B B B B _
_ _ G G G G G G G G G G G G G G C B B B B B B B B B B B B B B _ _
_ _ _ G G G G G G G G G G G G G _ B B B B B B B B B B B B B _ _ _
_ _ _ _ G G G G G G G G G G G _ _ _ B B B B B B B B B B B _ _ _ _
_ _ _ _ _ _ G G G G G G G _ _ _ _ _ _ _ B B B B B B B _ _ _ _ _ _
